var newkana = [
	/* ケセン語仮名 */
	["", "すﾒ", "すﾒ", "すﾒ", "&すメ;", "Hiragana Letter Kesen Si"],
	["", "ずﾒ", "ずﾒ", "ずﾒ", "&ずメ;", "Hiragana Letter Kesen Zi"],
	["", "ちﾒ", "ちﾒ", "ちﾒ", "&ちメ;", "Hiragana Letter Kesen Ti"],
	["", "ぢﾒ", "ぢﾒ", "ぢﾒ", "&ぢメ;", "Hiragana Letter Kesen Di"],
	["", "す゚ﾒ", "す゚ﾒ", "すﾟﾒ", "&す゜メ;", "Hiragana Letter Pinyin Shi"],
	["", "ずﾟﾒ", "ずﾟﾒ", "ずﾟﾒ", "&ず゜メ;", "Hiragana Letter Pinyin Ri"],
	["", "ち゚ﾒ", "ち゚ﾒ", "ちﾟﾒ", "&ち゜メ;", "Hiragana Letter Kesen Ti With Semi-Voiced Sound Mark"],
	["", "ぢﾟﾒ", "ぢﾟﾒ", "ぢﾟﾒ", "&ぢ゜メ;", "Hiragana Letter Pinyin Zhi"],
	["", "ち̣ﾒ", "ち̣ﾒ", "ち･ﾒ", "&ち.メ;", "Hiragana Letter Pinyin Ci"],
	["", "ち゚̣ﾒ", "ち゚̣ﾒ", "ちﾟ･ﾒ", "&ち゜.メ;", "Hiragana Letter Pinyin Chi"],

	["", "シﾒ", "シﾒ", "シﾒ", "&シメ;", "Katakana Letter Kesen Si"],
	["", "ジﾒ", "ジﾒ", "ジﾒ", "&ジメ;", "Katakana Letter Kesen Zi"],
	["", "ツﾒ", "ツﾒ", "ツﾒ", "&ツメ;", "Katakana Letter Kesen Ti"],
	["", "ヅﾒ", "ヅﾒ", "ヅﾒ", "&ヅメ;", "Katakana Letter Kesen Di"],
	["", "シ゚ﾒ", "シ゚ﾒ", "シﾟﾒ", "&シ゜メ;", "Katakana Letter Pinyin Shi"],
	["", "ジﾟﾒ", "ジﾟﾒ", "ジﾟﾒ", "&ジ゜メ;", "Katakana Letter Pinyin Ri"],
	["", "ツ゚ﾒ", "ツ゚ﾒ", "ツﾟﾒ", "&ツ゜メ;", "Katakana Letter Kesen Ti With Semi-Voiced Sound Mark"],
	["", "ヅﾟﾒ", "ヅﾟﾒ", "ヅﾟﾒ", "&ヅ゜メ;", "Katakana Letter Pinyin Zhi"],
	["", "ツ̣ﾒ", "ツ̣ﾒ", "ツ･ﾒ", "&ツ.メ;", "Katakana Letter Pinyin Ci"],
	["", "ツ゚̣ﾒ", "ツ゚̣ﾒ", "ツﾟ･ﾒ", "&ツ゜.メ;", "Katakana Letter Pinyin Chi"],

	/* ひらがな */
	["", "か゚", "か゚", "かﾟ", "か゜", "Hiragana Letter Nga"],
	["", "き゚", "き゚", "きﾟ", "き゜", "Hiragana Letter Ngi"],
	["", "く゚", "く゚", "くﾟ", "く゜", "Hiragana Letter Ngu"],
	["", "け゚", "け゚", "けﾟ", "け゜", "Hiragana Letter Nge"],
	["", "こ゚", "こ゚", "こﾟ", "こ゜", "Hiragana Letter Ngo"],
	["", "さ゚", "さ゚", "さﾟ", "さ゜", "Hiragana Letter Tha"],
	["", "ざﾟ", "ざﾟ", "ざﾟ", "ざ゜", "Hiragana Letter Dha"],
	["", "すｨ", "すｨ", "すｨ", "&すぃ;", "Hiragana Letter Si"],
	["", "ずｨ", "ずｨ", "ずｨ", "&ずぃ;", "Hiragana Letter Zi"],
	["", "す゚ｨ", "す゚ｨ", "すﾟｨ", "&す゜ぃ;", "Hiragana Letter Thi"],
	["", "ずﾟｨ", "ずﾟｨ", "ずﾟｨ", "&ず゜ぃ;", "Hiragana Letter Dhi"],
	["", "す゚", "す゚", "すﾟ", "す゜", "Hiragana Letter Thu"],
	["", "ずﾟ", "ずﾟ", "ずﾟ", "ず゜", "Hiragana Letter Dhu"],
	["", "せ゚", "せ゚", "せﾟ", "せ゜", "Hiragana Letter The"],
	["", "ぜﾟ", "ぜﾟ", "ぜﾟ", "ぜ゜", "Hiragana Letter Dhe"],
	["", "そ゚", "そ゚", "そﾟ", "そ゜", "Hiragana Letter Tho"],
	["", "ぞﾟ", "ぞﾟ", "ぞﾟ", "ぞ゜", "Hiragana Letter Dho"],
	["𛁃", "𛁃", "しｬ", "しｬ", "&しゃ;", "Hiragana Letter Sha"],
	["", "𛁃゙", "じｬ", "じｬ", "&じゃ;", "Hiragana Letter Ja"],
	["", "し゚", "し゚", "しﾟ", "し゜", "Hiragana Letter Shi With Voiced Sound Mark"],
	["", "しｭ", "しｭ", "しｭ", "&しゅ;", "Hiragana Letter Shu"],
	["", "じｭ", "じｭ", "じｭ", "&じゅ;", "Hiragana Letter Ju"],
	["", "しｪ", "しｪ", "しｪ", "&しぇ;", "Hiragana Letter She"],
	["", "じｪ", "じｪ", "じｪ", "&じぇ;", "Hiragana Letter Je"],
	["", "しｮ", "しｮ", "しｮ", "&しょ;", "Hiragana Letter Sho"],
	["", "じｮ", "じｮ", "じｮ", "&じょ;", "Hiragana Letter Jo"],
	["", "てｨ", "てｨ", "てｨ", "&てぃ;", "Hiragana Letter Ti"],
	["", "でｨ", "でｨ", "でｨ", "&でぃ;", "Hiragana Letter Di"],
	["𛁭", "𛁭", "とｩ", "とｩ", "&とぅ;", "Hiragana Letter Tu"],
	["", "𛁭゙", "どｩ", "どｩ", "&どぅ;", "Hiragana Letter Du"],
	["", "ちｬ", "ちｬ", "ちｬ", "&ちゃ;", "Hiragana Letter Cha"],
	["", "ぢｬ", "ぢｬ", "ぢｬ", "&ぢゃ;", "Hiragana Letter Dja"],
	["", "ちｭ", "ちｭ", "ちｭ", "&ちゅ;", "Hiragana Letter Chu"],
	["", "ぢｭ", "ぢｭ", "ぢｭ", "&ぢゅ;", "Hiragana Letter Dju"],
	["", "ちｪ", "ちｪ", "ちｪ", "&ちぇ;", "Hiragana Letter Che"],
	["", "ぢｪ", "ぢｪ", "ぢｪ", "&ぢぇ;", "Hiragana Letter Dje"],
	["", "ちｮ", "ちｮ", "ちｮ", "&ちょ;", "Hiragana Letter Cho"],
	["", "ぢｮ", "ぢｮ", "ぢｮ", "&ぢょ;", "Hiragana Letter Djo"],
	["", "つｧ", "つｧ", "つｧ", "&つぁ;", "Hiragana Letter Tsa"],
	["", "づｧ", "づｧ", "づｧ", "&づぁ;", "Hiragana Letter Dza"],
	["", "つｨ", "つｨ", "つｨ", "&つぃ;", "Hiragana Letter Tsi"],
	["", "づｨ", "づｨ", "づｨ", "&づぃ;", "Hiragana Letter Dzi"],
	["", "つｪ", "つｪ", "つｪ", "&つぇ;", "Hiragana Letter Tse"],
	["", "づｪ", "づｪ", "づｪ", "&づぇ;", "Hiragana Letter Dze"],
	["", "つｫ", "つｫ", "つｫ", "&つぉ;", "Hiragana Letter Tso"],
	["", "づｫ", "づｫ", "づｫ", "&づぉ;", "Hiragana Letter Dzo"],
	["𛀹", "𛀹", "ほｩ", "ほｩ", "&ほぅ;", "Hiragana Letter Hu-2"],
	["𛀆", "𛀆", "いｨ", "いｨ", "&いぃ;", "Hiragana Letter Yi"],
	["𛀁", "𛀁", "いｪ", "いｪ", "&いぇ;", "Hiragana Letter Ye"],
	["", "ら゚", "ら゚", "らﾟ", "ら゜", "Hiragana Letter La"],
	["", "り゚", "り゚", "りﾟ", "り゜", "Hiragana Letter Li"],
	["", "る゚", "る゚", "るﾟ", "る゜", "Hiragana Letter Lu"],
	["", "れ゚", "れ゚", "れﾟ", "れ゜", "Hiragana Letter Le"],
	["", "ろ゚", "ろ゚", "ろﾟ", "ろ゜", "Hiragana Letter Lo"],
	["", "わ゙", "わ゙", "わﾞ", "わ゛", "Hiragana Letter Va"],
	["", "わ゚", "わ゚", "わﾟ", "わ゜", "Hiragana Letter Fa"],
	["ゐ", "ゐ", "ゐ", "ゐ", "&うぃ;", "Hiragana Letter Wi"],
	["", "ゐ゙", "ゐ゙", "ゐﾞ", "&う゛ぃ;", "Hiragana Letter Vi"],
	["", "ゐ゚", "ゐ゚", "ゐﾟ", "&う゜ぃ;", "Hiragana Letter Fi"],
	["𛄟", "𛄟", "うｩ", "うｩ", "&うぅ;", "Hiragana Letter Wu"],
	["", "𛄟゙", "ゔｩ", "うﾞｩ", "&う゛ぅ;", "Hiragana Letter Vu"],
	["", "𛄟゚", "う゚ｩ", "うﾟｩ", "&う゜ぅ;", "Hiragana Letter Fu"],
	["ゑ", "ゑ", "ゑ", "ゑ", "&うぇ;", "Hiragana Letter We"],
	["", "ゑ゙", "ゑ゙", "ゑﾞ", "&う゛ぇ;", "Hiragana Letter Ve"],
	["", "ゑ゚", "ゑ゚", "ゑﾟ", "&う゜ぇ;", "Hiragana Letter Fe"],
	["", "を゙", "を゙", "をﾞ", "を゛", "Hiragana Letter Vo"],
	["", "を゚", "を゚", "をﾟ", "を゜", "Hiragana Letter Fo"],
	["ゔ", "ゔ", "ゔ", "うﾞ", "う゛", "Hiragana Letter Vu"],
	["", "ふﾝ", "ふﾝ", "ふﾝ", "&ふん;", "Hiragana Letter Hn"],
	["", "ぶﾝ", "ぶﾝ", "ぶﾝ", "&ぶん;", "Hiragana Letter Bn"],
	["", "ちｯ", "ちｯ", "ちｯ", "&ちっ;", "Hiragana Letter Tsk"],

	/* カタカナ */
	["", "カ゚", "カ゚", "カﾟ", "カ゜", "Katakana Letter Nga"],
	["", "キ゚", "キ゚", "キﾟ", "キ゜", "Katakana Letter Ngi"],
	["", "ク゚", "ク゚", "クﾟ", "ク゜", "Katakana Letter Ngu"],
	["", "ケ゚", "ケ゚", "ケﾟ", "ケ゜", "Katakana Letter Nge"],
	["", "コ゚", "コ゚", "コﾟ", "コ゜", "Katakana Letter Ngo"],
	["", "サ゚", "サ゚", "サﾟ", "サ゜", "Katakana Letter Tha"],
	["", "ザﾟ", "ザﾟ", "ザﾟ", "ザ゜", "Katakana Letter Dha"],
	["", "スｨ", "スｨ", "スｨ", "&スィ;", "Katakana Letter Si"],
	["", "ズｨ", "ズｨ", "ズｨ", "&ズィ;", "Katakana Letter Zi"],
	["", "ス゚ｨ", "ス゚ｨ", "スﾟｨ", "&ス゜ィ;", "Katakana Letter Thi"],
	["", "ズﾟｨ", "ズﾟｨ", "ズﾟｨ", "&ズ゜ィ;", "Katakana Letter Dhi"],
	["", "ス゚", "ス゚", "スﾟ", "ス゜", "Katakana Letter Thu"],
	["", "ズﾟ", "ズﾟ", "ズﾟ", "ズ゜", "Katakana Letter Dhu"],
	["", "セ゚", "セ゚", "セﾟ", "セ゜", "Katakana Letter The"],
	["", "ゼﾟ", "ゼﾟ", "ゼﾟ", "ゼ゜", "Katakana Letter Dhe"],
	["", "ソ゚", "ソ゚", "ソﾟ", "ソ゜", "Katakana Letter Tho"],
	["", "ゾﾟ", "ゾﾟ", "ゾﾟ", "ゾ゜", "Katakana Letter Dho"],
	["", "シｬ", "シｬ", "シｬ", "&シャ;", "Katakana Letter Sha"],
	["", "ジｬ", "ジｬ", "ジｬ", "&ジャ;", "Katakana Letter Ja"],
	["", "シ゚", "シ゚", "シﾟ", "シ゜", "Katakana Letter Shi With Voiced Sound Mark"],
	["", "シｭ", "シｭ", "シｭ", "&シュ;", "Katakana Letter Shu"],
	["", "ジｭ", "ジｭ", "ジｭ", "&ジュ;", "Katakana Letter Ju"],
	["", "シｪ", "シｪ", "シｪ", "&シェ;", "Katakana Letter She"],
	["", "ジｪ", "ジｪ", "ジｪ", "&ジェ;", "Katakana Letter Je"],
	["", "シｮ", "シｮ", "シｮ", "&ショ;", "Katakana Letter Sho"],
	["", "ジｮ", "ジｮ", "ジｮ", "&ジョ;", "Katakana Letter Jo"],
	["", "テｨ", "テｨ", "テｨ", "&ティ;", "Katakana Letter Ti"],
	["", "デｨ", "デｨ", "デｨ", "&ディ;", "Katakana Letter Di"],
	["", "トｩ", "トｩ", "トｩ", "&トゥ;", "Katakana Letter Tu"],
	["", "ドｩ", "ドｩ", "ドｩ", "&ドゥ;", "Katakana Letter Du"],
	["", "ト゚", "ト゚", "トﾟ", "ト゜", "Katakana Letter To With Voiced Sound Mark"],
	["", "チｬ", "チｬ", "チｬ", "&チャ;", "Katakana Letter Cha"],
	["", "ヂｬ", "ヂｬ", "ヂｬ", "&ヂャ;", "Katakana Letter Dja"],
	["", "チｭ", "チｭ", "チｭ", "&チュ;", "Katakana Letter Chu"],
	["", "ヂｭ", "ヂｭ", "ヂｭ", "&ヂュ;", "Katakana Letter Dju"],
	["", "チｪ", "チｪ", "チｪ", "&チェ;", "Katakana Letter Che"],
	["", "ヂｪ", "ヂｪ", "ヂｪ", "&ヂェ;", "Katakana Letter Dje"],
	["", "チｮ", "チｮ", "チｮ", "&チョ;", "Katakana Letter Cho"],
	["", "ヂｮ", "ヂｮ", "ヂｮ", "&ヂョ;", "Katakana Letter Djo"],
	["", "ツｧ", "ツｧ", "ツｧ", "&ツァ;", "Katakana Letter Tsa"],
	["", "ヅｧ", "ヅｧ", "ヅｧ", "&ヅァ;", "Katakana Letter Dza"],
	["", "ツｨ", "ツｨ", "ツｨ", "&ツィ;", "Katakana Letter Tsi"],
	["", "ヅｨ", "ヅｨ", "ヅｨ", "&ヅィ;", "Katakana Letter Dzi"],
	["", "ツ゚", "ツ゚", "ツﾟ", "ツ゜", "Katakana Letter Tsu With Voiced Sound Mark"],
	["", "ツｪ", "ツｪ", "ツｪ", "&ツェ;", "Katakana Letter Tse"],
	["", "ヅｪ", "ヅｪ", "ヅｪ", "&ヅェ;", "Katakana Letter Dze"],
	["", "ツｫ", "ツｫ", "ツｫ", "&ツォ;", "Katakana Letter Tso"],
	["", "ヅｫ", "ヅｫ", "ヅｫ", "&ヅォ;", "Katakana Letter Dzo"],
	["", "ホｩ", "ホｩ", "ホｩ", "&ホゥ;", "Katakana Letter Hu-2"],
	["𛄠", "𛄠", "イｨ", "イｨ", "&イィ;", "Katakana Letter Yi"],
	["𛄡", "𛄡", "イｪ", "イｪ", "&イェ;", "Katakana Letter Ye"],
	["", "ラ゚", "ラ゚", "ラﾟ", "ラ゜", "Katakana Letter La"],
	["", "リ゚", "リ゚", "リﾟ", "リ゜", "Katakana Letter Li"],
	["", "ル゚", "ル゚", "ルﾟ", "ル゜", "Katakana Letter Lu"],
	["", "レ゚", "レ゚", "レﾟ", "レ゜", "Katakana Letter Le"],
	["", "ロ゚", "ロ゚", "ロﾟ", "ロ゜", "Katakana Letter Lo"],
	["ヮ", "ヮ", "ヮ", "ヮ", "&ゥァ;", "Katakana Letter Small Wa"],
	["ヷ", "ヷ", "ヷ", "ワﾞ", "ワ゛", "Katakana Letter Va"],
	["", "ワ゚", "ワ゚", "ワﾟ", "ワ゜", "Katakana Letter Fa"],
	["ヰ", "ヰ", "ヰ", "ヰ", "&ウィ;", "Katakana Letter Wi"],
	["ヸ", "ヸ", "ヸ", "ヰﾞ", "&ヴィ;", "Katakana Letter Vi"],
	["", "ヰ゚", "ヰ゚", "ヰﾟ", "&ウ゜ィ;", "Katakana Letter Fi"],
	["𛄢", "𛄢", "ウｩ", "ウｩ", "&ウゥ;", "Katakana Letter Wu"],
	["", "𛄢゙", "ヴｩ", "ヴｩ", "&ヴゥ;", "Katakana Letter Vu"],
	["", "𛄢゚", "ウ゚ｩ", "ウﾟｩ", "&ウ゜ゥ;", "Katakana Letter Fu"],
	["ヱ", "ヱ", "ヱ", "ヱ", "&ウェ;", "Katakana Letter We"],
	["ヹ", "ヹ", "ヹ", "ヱﾞ", "&ヴェ;", "Katakana Letter Ve"],
	["", "ヱ゚", "ヱ゚", "ヱﾟ", "&ウ゜ェ;", "Katakana Letter Fe"],
	["ヺ", "ヺ", "ヺ", "ヲﾞ", "ヲ゛", "Katakana Letter Vo"],
	["", "ヲ゚", "ヲ゚", "ヲﾟ", "ヲ゜", "Katakana Letter Fo"],
	["", "フﾝ", "フﾝ", "フﾝ", "&フン;", "Katakana Letter Hn"],
	["", "ブﾝ", "ブﾝ", "ブﾝ", "&ブン;", "Katakana Letter Bn"],
	["", "チｯ", "チｯ", "チｯ", "&チッ;", "Katakana Letter Tsk"],

	/* 小書きひらがな */
	["ゕ", "ゕ", "ゕ", "ﾁか", "&チか;", "Hiragana Letter Small Ka"],
	["ゖ", "ゖ", "ゖ", "ﾁけ", "&チけ;", "Hiragana Letter Small Ke"],
	["𛄲", "𛄲", "ﾁこ", "ﾁこ", "&チこ;", "Hiragana Letter Small Ko"],
	["𛅄", "ﾁへ", "ﾁへ", "ﾁへ", "&チへ;", "Hiragana Letter Small He"],
	["󷰸", "ぃｨ", "ぃｨ", "ぃｨ", "&ぃぃ;", "Hiragana Letter Small Yi"],
	["󷰹", "ぃｪ", "ぃｪ", "ぃｪ", "&ぃぇ;", "Hiragana Letter Small Ye"],
	["ゎ", "ゎ", "ゎ", "ゎ", "&ぅぁ;", "Hiragana Letter Small Wa"],
	["𛅐", "𛅐", "ぅｨ", "ぅｨ", "&ぅぃ;", "Hiragana Letter Small Wi"],
	["󷰺", "ぅｩ", "ぅｩ", "ぅｩ", "&ぅぅ;", "Hiragana Letter Small Wu"],
	["𛅑", "𛅑", "ぅｪ", "ぅｪ", "&ぅぇ;", "Hiragana Letter Small We"],
	["𛅒", "𛅒", "ぅｫ", "ぅｫ", "&ぅぉ;", "Hiragana Letter Small Wo"],
	["𛅓", "ﾁん", "ﾁん", "ﾁん", "&チん;", "Hiragana Letter Small N"],

	/* 小書きカタカナ */
	["𛅕", "𛅕", "ﾁコ", "ﾁコ", "&チコ;", "Katakana Letter Small Ko"],
	["ㇰ", "ㇰ", "ㇰ", "ﾁク", "&チク;", "Katakana Letter Small Ku"],
	["ㇱ", "ㇱ", "ㇱ", "ﾁシ", "&チシ;", "Katakana Letter Small Shi"],
	["ㇲ", "ㇲ", "ㇲ", "ﾁス", "&チス;", "Katakana Letter Small Su"],
	["ㇳ", "ㇳ", "ㇳ", "ﾁト", "&チト;", "Katakana Letter Small To"],
	["ㇴ", "ㇴ", "ㇴ", "ﾁヌ", "&チヌ;", "Katakana Letter Small Nu"],
	["ㇵ", "ㇵ", "ㇵ", "ﾁハ", "&チハ;", "Katakana Letter Small Ha"],
	["ㇶ", "ㇶ", "ㇶ", "ﾁヒ", "&チヒ;", "Katakana Letter Small Hi"],
	["ㇷ", "ㇷ", "ㇷ", "ﾁフ", "&チフ;", "Katakana Letter Small Hu"],
	["", "ㇷ゚", "ㇷ゚", "ﾁプ", "&チプ;", "Katakana Letter Small Pu"],
	["ㇸ", "ㇸ", "ㇸ", "ﾁヘ", "&チヘ;", "Katakana Letter Small He"],
	["ㇹ", "ㇹ", "ㇹ", "ﾁホ", "&チホ;", "Katakana Letter Small Ho"],
	["ㇺ", "ㇺ", "ㇺ", "ﾁム", "&チム;", "Katakana Letter Small Mu"],
	["󷰻", "ィｨ", "ィｨ", "ィｨ", "&ィィ;", "Katakana Letter Small Yi"],
	["󷰼", "ィｪ", "ィｪ", "ィｪ", "&ィェ;", "Katakana Letter Small Ye"],
	["ㇻ", "ㇻ", "ㇻ", "ﾁラ", "&チラ;", "Katakana Letter Small Ra"],
	["ㇼ", "ㇼ", "ㇼ", "ﾁリ", "&チリ;", "Katakana Letter Small Ri"],
	["ㇽ", "ㇽ", "ㇽ", "ﾁル", "&チル;", "Katakana Letter Small Ru"],
	["ㇾ", "ㇾ", "ㇾ", "ﾁレ", "&チレ;", "Katakana Letter Small Re"],
	["ㇿ", "ㇿ", "ㇿ", "ﾁロ", "&チロ;", "Katakana Letter Small Ro"],
	["𛅤", "𛅤", "ゥｨ", "ゥｨ", "&ゥィ;", "Katakana Letter Small Wi"],
	["󷰽", "ゥｩ", "ゥｩ", "ゥｩ", "&ゥゥ;", "Katakana Letter Small Wu"],
	["𛅥", "𛅥", "ゥｪ", "ゥｪ", "&ゥェ;", "Katakana Letter Small We"],
	["𛅦", "𛅦", "ゥｫ", "ゥｫ", "&ゥォ;", "Katakana Letter Small Wo"],
	["𛅧", "𛅧", "ﾁン", "ﾁン", "&チン;", "Katakana Letter Small N"],

	/* 母音拡張記号付きひらがな */
	["", "ぁ̬", "ぁ̬", "ぁ^", "ぁ^", "Hiragana Letter Small Ax"],
	["", "あ̬", "あ̬", "あ^", "あ^", "Hiragana Letter Ax"],
	["", "ぃ̬", "ぃ̬", "ぃ^", "ぃ^", "Hiragana Letter Small Ix"],
	["", "い̬", "い̬", "い^", "い^", "Hiragana Letter Ix"],
	["", "ぅ̬", "ぅ̬", "ぅ^", "ぅ^", "Hiragana Letter Small Ux"],
	["", "う̬", "う̬", "う^", "う^", "Hiragana Letter Ux"],
	["", "ぇ̬", "ぇ̬", "ぇ^", "ぇ^", "Hiragana Letter Small Ex"],
	["", "え̬", "え̬", "え^", "え^", "Hiragana Letter Ex"],
	["", "ぉ̬", "ぉ̬", "ぉ^", "ぉ^", "Hiragana Letter Small Ox"],
	["", "お̬", "お̬", "お^", "お^", "Hiragana Letter Ox"],

	/* 母音拡張記号付きカタカナ */
	["", "ァ̬", "ァ̬", "ァ^", "ァ^", "Katakana Letter Small Ax"],
	["", "ア̬", "ア̬", "ア^", "ア^", "Katakana Letter Ax"],
	["", "ィ̬", "ィ̬", "ィ^", "ィ^", "Katakana Letter Small Ix"],
	["", "イ̬", "イ̬", "イ^", "イ^", "Katakana Letter Ix"],
	["", "ゥ̬", "ゥ̬", "ゥ^", "ゥ^", "Katakana Letter Small Ux"],
	["", "ウ̬", "ウ̬", "ウ^", "ウ^", "Katakana Letter Ux"],
	["", "ェ̬", "ェ̬", "ェ^", "ェ^", "Katakana Letter Small Ex"],
	["", "エ̬", "エ̬", "エ^", "エ^", "Katakana Letter Ex"],
	["", "ォ̬", "ォ̬", "ォ^", "ォ^", "Katakana Letter Small Ox"],
	["", "オ̬", "オ̬", "オ^", "オ^", "Katakana Letter Ox"],

	/* 下点付き小書き仮名 */
	["", "ぃ̣", "ぃ̣", "ぃ･", "&ぃ.;", "Hiragana Letter Small I With Dot Below"],
	["", "ぅ̣", "ぅ̣", "ぅ･", "&ぅ.;", "Hiragana Letter Small U With Dot Below"],
	["", "ィ̣", "ィ̣", "ィ･", "&ィ.;", "Katakana Letter Small I With Dot Below"],
	["", "ゥ̣", "ゥ̣", "ゥ･", "&ゥ.;", "Katakana Letter Small U With Dot Below"],

	/* 記号 */
	["゙", "゙", "゙", "ﾞ", "゛", "Combining Katakana-Hiragana Voiced Sound Mark"],
	["゚", "゚", "゚", "ﾟ", "゜", "Combining Katakana-Hiragana Semi-Voiced Sound Mark"],
	["", "゙ﾟ", "゙ﾟ", "ﾞﾟ", "゛゜", "Combining Katakana-Hiragana Voiced Semi-Voiced Sound Mark"],
	["", "゛ﾟ", "゛ﾟ", "゛ﾟ", "゛゜", "Katakana-Hiragana Voiced Semi-Voiced Sound Mark"],
	["", "ﾞﾟ", "ﾞﾟ", "ﾞﾟ", "゛゜", "Halfwidth Katakana-Hiragana Voiced Semi-Voiced Sound Mark"],
	["", "̣", "̣", "･", ".;", "Combining Katakana Dot Below"],
	["", "̬", "̬", "^", "^", "Combining Katakana Caron Below"],
	["゠", "゠", "゠", "＝", "＝", "Katakana-Hiragana Double Hyphen"]
];